spring:
  application:
    name: service-server

switchable:
  feature-on: false
  test-kafka-stream-server: localhost:9092
kafka:
  cluster1:
    bootstrap-servers: kafka1:9092
  cluster2:
    bootstrap-servers: kafka2:9093
