spring:
  application:
    name: admin-server
  datasource:
    url: jdbc:mysql://mysql:3306/sample
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

kafka:
  cluster1:
    bootstrap-servers: kafka1:9092
  cluster2:
    bootstrap-servers: kafka2:9093
