spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT property_key, property_value FROM properties WHERE application = ? AND profile=? AND label=?
          order: 0
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
