spring:
  application:
    name: cloud-config-server
  profiles:
    include: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT property_key, property_value FROM properties WHERE application = ? AND profile=? AND label=?
          order: 0
  datasource:
    url: jdbc:mysql://mysql:3306/sample
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
